### ISSUE TITLE
SchedulingConfigurer中怎么设置注册的定时任务为异步执行呢

### ISSUE THREAD

**Issue by jitao0502** [liyupi/yu-auto-reply#2]
![image](https://user-images.githubusercontent.com/59304364/227761850-73cf7ea0-a72b-4611-b651-a3376a56b15b.png)

**Comment by liyupi** [comment]
定时任务本来就是异步的。。你想问什么

**Comment by jitao0502** [comment]
> 定时任务本来就是不对的。。你想问什么

就是想了解下使用SchedulingConfigurer这种方式注册定时任务，能不能设置定时任务为异步执行

**Comment by jitao0502** [comment]
> 就是想了解下载使用SchedulingConfigurer这种方式注册表指定时间任务，不能设置时间任务为异常操作

上一句打错了，就是想了解下使用SchedulingConfigurer这种方式注册定时间任务，能不能设置定时任务为异步执行

**Comment by jitao0502** [comment]
就是想了解下使用SchedulingConfigurer这种方式注册定时任务，能不能设置定时任务为异步执行

**Comment by liyupi** [comment]
建议你去问问百度吧，和项目本身问题无关的问题 😂

**Comment by jitao0502** [comment]
> 建议你去问百度吧，和项目本身问题无关的问题😂

那你这种注册定时任务得方式不是会存在定时任务阻塞得问题么

**Comment by liyupi** [comment]
> > 建议你去问百度吧，和项目本身问题无关的问题😂
> 
> 那你这种注册定时任务得方式不是会存在定时任务阻塞得问题么

默认是阻塞的，前期本来设计如此，减少一些不必要的冲突，让输出更可读。
还是建议这种问题和项目业务无关的问题自己去百度一下，网上的答案明明一抓一大把：https://www.51cto.com/article/697762.html

另外，我帮大家补一行线程池代码吧

**Comment by liyupi** [comment]
> > 建议你去问百度吧，和项目本身问题无关的问题😂
> 
> 那你这种注册定时任务得方式不是会存在定时任务阻塞得问题么

已支持灵活配置并发：https://github.com/liyupi/yu-auto-reply/blob/master/src/main/resources/application.yml ，感兴趣欢迎帮忙测试

**Comment by jitao0502** [comment]
一抓一把并不一定正确呀，如果你试过你发的博客那个设置线程池方式，其实是没用的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月27日(周一) 上午10:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liyupi/yu-auto-reply] SchedulingConfigurer中怎么设置注册的定时任务为异步执行呢 (Issue #2)




   
建议你去问百度吧，和项目本身问题无关的问题😂
  
那你这种注册定时任务得方式不是会存在定时任务阻塞得问题么
  
默认是阻塞的，前期本来设计如此，减少一些不必要的冲突，让输出更可读。
 还是建议这种问题和项目业务无关的问题自己去百度一下，网上的答案明明一抓一大把：https://www.51cto.com/article/697762.html
 
另外，我帮大家补一行线程池代码吧

**Comment by liyupi** [comment]
你测试下我最新的提交就好了

**Comment by jitao0502** [comment]
好的，我晚上回去看看，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月27日(周一) 中午12:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liyupi/yu-auto-reply] SchedulingConfigurer中怎么设置注册的定时任务为异步执行呢 (Issue #2)




 
你测试下我最新的提交就好了
